version: '3.8'

services:
  db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_HOST=fastapi-postgres-db-1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    #env_file:
    #  - .env
    restart: always
    
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    #environment:
    #  - POSTGRES_HOST=DATABASE_HOSTNAME
    #  - POSTGRES_DB=DATABASE_NAME
    #  - POSTGRES_USER=DATABASE_USERNAME
    #  - POSTGRES_PASSWORD=DATABASE_PASSWORD
    #env_file:
    #  - .env
    depends_on:
      - db
    restart: always

  


volumes:
  db:
    driver: local


